#!/usr/bin/env zsh
# shellcheck shell=bash

dev () { #: prepare stuff and watch
	trap './task prod; exit 0' SIGINT

	php -S localhost:8000 -t _source &
	bunx tailwindcss -i _source/main.css -o _source/main.out.css --watch
}

prod () { #: run through the whole pipeline
	bunx tailwindcss -i _source/main.css -o _source/main.min.css --minify
	php -S localhost:8000 -t _source &
	http 'localhost:8000/?build' > index.html
	kill -9 $(pgrep -f 'localhost:8000')
}

#
# BOILERPLATE
#
r='./task'
NAME='histaminy.adamkiss.com'

about () { #: show help & commands
    echo "$NAME script runner"
    echo "Commands:"
    sed -nr 's/^(.*) \(\).* #: (.*)$/  \1\t\2/p' $r | expand -20
	# this sed looks crazy, but it just parses this file
	# and finds lines with `() #: ` and prints them in a nice format
}

if [[ $# -gt 0 ]]; then
	command="$1"
	shift 1
	if type "$command" 2>/dev/null | grep -q 'function'; then
		$command "$@"
	else
		about
		echo "No command '$command'."
	fi;
else
    # task to run by default if no arguments are passed
	dev
fi
